import turtle


Screen=turtle.Screen()
Screen.bgcolor('cyan')
Screen.title('my first drawing')
pen=turtle.Turtle()
# pen.shape('turtle')
pen.fillcolor('red')
pen.color("white")
# pen.shape('square')
# pen.width(30)
pen.forward(200)
# pen.width(20)
pen.speed(200000)
pen.left(90)
pen.forward(200)
pen.left(90)
pen.forward(200)
pen.left(90)
pen.forward(200)
turtle.done()
# pen.up()
# pen.goto(50,50)